on:
  push:
      branches:
        - master
name: Postman collection

jobs:

  generate:
    name: Update postman collection

    runs-on: ubuntu-latest

    steps:
      - name: Checkout api reference
        uses: actions/checkout@v2
        with:
          path: api

      - name: Checkout postman collection
        uses: actions/checkout@v2
        with:
          repository: 'commercetools/commercetools-postman-collection'
          path: postman

      - name: Generate postman collection
        run: docker run --rm -v"$PWD/api":/api -v"$PWD/postman":/out vrapio/rmf-codegen generate -o /out/api -t postman /api/postman.raml

      - name: clean postman folder
        run: cd postman && git checkout -- api/gen.properties

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: postman
          commit_message: "TASK: Updating Postman collection"
          commit_user_name: Auto Mation
          commit_user_email: automation@commercetools.com
          commit_author: Auto Mation <automation@commercetools.com>
